### ISSUE TITLE
Support DELETE on Integrations

### ISSUE THREAD

**Issue by saj** [PagerDuty/pagerduty-api-python-client#16]
In PagerDuty support case #85888, I received confirmation that the v2 API does, in fact, support the deletion of individual integrations (on a service).  The `Integration` class in this library rejects deletes.  (The `delete` and `remove` methods are explicitly overridden to raise `InvalidEndpoint` and `InvalidEndpointOperation` exceptions, respectively.)  That's one problem.

The second problem involves the resource paths for integrations.  These paths are nested beneath their parent services.  e.g.: `/services/SERVICE-ID/integrations/INTEGRATION-ID`.  The default `Entity` endpoint resolution code does not work in this case.  Even if the overridden `delete` and `remove` methods were to be removed, resource deletion would fail because the requests would be addressed to `/integrations/INTEGRATION-ID` (missing leading `/services/SERVICE-ID`).  I'm not sure how best to solve this problem.   Endpoints seem to get resolved at the class layer when what (I think) we need here is resolution at the instance layer.

Thoughts?

**Comment by jdcumpson** [comment]
Thanks for the feedback - as for the `InvalidEndpointOperation` it was intentional for reason of it had no proper endpoint documentation. On the upside, I've raised this concern with the appropriate people and hopefully that will indeed be rectified. I'm not against implementation, however as a good Dutonian I have to make sure I'm doing the organization justice (not supporting dead API things). TL;DR - it's being looked into.

As for the second problem - I suspect when I first started that problem one was a good scape goat for this problem. As in the `fetch` method, I suspect the _cheap_ way to solve this is require a `Service` or service ID as a parameter. Indeed this breaks interfaces, but so does the `Integration` class only being accessible via service.

```python
@classmethod
# psuedo  py code
def delete(cls, id, service=None, endpoint=None, ...):
    ...

remove = delete
```

**Comment by jdcumpson** [comment]
@saj following up on this item - as of now this still isn't updated in the public API documentation however, the documentation should be updated soon. I'm good to get this one underway if anyone is willing to give it a go.

**Comment by bzmw** [comment]
Hey there, 
Thanks for your contribution but we decided to deprecate this project. Please use [PDPyras](https://github.com/PagerDuty/pdpyras) instead.
