### ISSUE TITLE
Improve consistency between API requests and responses

### ISSUE THREAD

**Issue by mikhail** [PagerDuty/pagerduty-api-python-client#30]
Trying to answer a question "who is on call for a given service" is proving to be a bit complicated.

```python
service = pypd.Service.find_one(name=service_name)

# Would like one of of the following to work in order of preference:
ep = service.get_escalation_policy()
ep = pypd.EscalationPolicy.find_one(service)
ep = pypd.EscalationPolicy.find_one(**service.json['escalation_policy'])
ep = pypd.EscalationPolicy.find_one(name=service.json['escalation_policy']['name'])

# ok fine, those don't work, maybe `id` works
ep = pypd.EscalationPolicy.find_one(id=service.json['escalation_policy']['id'])
# The API call works, but it returns a wrong EP :(
ep.id == service.json['escalation_policy']['id']   # False

# but really name = summary. so this works:
ep = pypd.EscalationPolicy.find_one(name=service.json['escalation_policy']['summary'])
```

Haven't even gotten to schedule and users. Am I missing something that makes this easier?

**Comment by jdcumpson** [comment]
Hey @mikhail. Thanks for bringing up a good question. I've investigated and there's a few pieces. 

The first thing is that the `v2` API doesn't always support parameters even if they're permitted via the `Entity` base class. In this case, `id` for `find_one` is passing through the `id` parameter but the API itself doesn't use it. That's why the `id` field lookup fails. There's no filtering done locally because it would be pretty hard to do that in a non-specific way. Although we could expose a hook to allow it on a per-entity-basis.

The second thing is that the thing you are getting back in your `Service` instance isn't actually the full `EscalationPolicy` it is the `EscalationPolicyReference`. Which includes `summary` which will be identical to name. You can see the schema for it on the v2 docs, the summary field is:

>A short-form, server-generated string that provides succinct, important information about an object suitable for primary labeling of an entity in a client. In many cases, this will be identical to `name`, though it is not intended to be an identifier.

And `EscalationPolicies` only have `id`, `summary`, `type`, `self`, `html_url` fields.

In this case the `TRANSLATE_QUERY_PARAM = ('name',)` turns the `name=` keyword argument into `query=` transparently on the `EscalationPolicy` class methods. A solution could be to have similar translations available or hooks. Also overriding the methods themselves is an option if it's too specific.

I do also think that there's some room for improvement around the `find(...)` and `find_one(...)` semantics. `find_one(...)` kind of assumes all filtering will be done server-side and that endpoint will return 1 result in which we use generator to return the first result. I think it would be reasonable to have local filtering transparently if the endpoint doesn't support arguments that make this very easy, like this case.

Do you have any thoughts about that?

**Comment by jdcumpson** [comment]
Also, you can use `Entity` (and by extension `Service`) classes as attribute-like objects, so you can do `service['escalation_policy']` is the same as `service.json['escalation_policy']`

**Comment by mikhail** [comment]
@jdcumpson thanks for your help! I found `EscalationPolicy.fetch()` which works on IDs, so the following works as expected:

```python
pypd.EscalationPolicy.fetch(**service.json['escalation_policy'])

# or per your note:
pypd.EscalationPolicy.fetch(id=service['escalation_policy']['id'])
```

**Comment by jdcumpson** [comment]
Alright I'll mark this as closed, thanks for answering your own question 😆
